version: '3.8'

services:
  web:
    build: .
    command: gunicorn helloworld_project.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on: []
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

# Optional local MySQL service (commented out because you will use RDS in AWS)
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#    ports:
#      - "3306:3306"
    